# Generated by Django 5.2.1 on 2025-08-27 15:30

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contexto',
            name='imagem_url',
        ),
        migrations.AddField(
            model_name='contexto',
            name='imagem',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='media'),
            preserve_default=False,
        ),
    ]
