# Generated by Django 5.2.1 on 2025-08-27 15:47

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_remove_contexto_imagem_url_contexto_imagem'),
    ]

    operations = [
        migrations.AddField(
            model_name='elenco',
            name='nascimento',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='elenco',
            name='personagem',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='contexto',
            name='imagem',
            field=models.ImageField(upload_to='website/media'),
        ),
    ]
