# Generated by Django 5.2.1 on 2025-08-27 16:10

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_elenco_nascimento_elenco_personagem_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contexto',
            name='imagem',
        ),
        migrations.RemoveField(
            model_name='elenco',
            name='foto',
        ),
        migrations.AddField(
            model_name='elenco',
            name='imagem',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='website/media/'),
            preserve_default=False,
        ),
    ]
